### ISSUE TITLE
A heads up

### ISSUE THREAD

**Issue by kkirby** [shustariov-andrey/grunt-cordova-config#6]
Hey,

I just wanted you to know that I took your project and ran with it: https://github.com/kkirby/grunt-cordova-config

I pretty much did a whole rewrite. I would of asked to merge in with yours, but my coding style is pretty different than yours and I found it pretty hard to maintain your style throughout.

Thanks for open-sourcing an awesome project!

**Comment by shustariov-andrey** [comment]
Hi!

Actually, your implementation looks much better, especially, considering rapidly evolving nature of cordova)

**Comment by shustariov-andrey** [comment]
So, if you still have intent to merge - just let me know

**Comment by kkirby** [comment]
Yeah, I would love to merge my stuff in. I'm currently working on a documentation generator so that when there are changes, the readme.md doesn't have to be manually updated, and this way it will actually be up-to-date according to the spec. I predict I should be done by Monday and I'll open up a PR after. You can see what I've come up with so far [here](https://github.com/kkirby/grunt-cordova-config/blob/rewrite/readme_tmp.md) which was generated using [documentationGenerator.js](https://github.com/kkirby/grunt-cordova-config/blob/rewrite/src/documentationGenerator.js)
